
```{r setup_CDB_MC, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(highcharter)

# DB SOCKET
db <- src_sqlite("~/R/evoapp/DB/cetip_db.sqlite3", create = FALSE)
# DB TABLES
tbl_CDB_mercado <- tbl(db,"b3_CDB_mercado")
tbl_CDB_santander <- tbl(db,"b3_CDB_santander")
tbl_oc_mercado <- tbl(db,"b3_oc_mercado")

dt_vct <- tbl_oc_mercado %>% distinct(DAT_REGISTRO) %>% filter(DAT_REGISTRO >= '2016-12-02') %>% collect()
dt_vct2 <- lubridate::ymd(dt_vct[[1]])

plot_vector <- as_tibble(read_rds('~/R/evoapp/DB/plot_vectors.rds'))
ts_San_Share_cdb <- xts::xts(round(plot_vector$vect_share_cdb,digits = 2),order.by = dt_vct2)
ts_delta_cdb <- xts::xts(round(plot_vector$vect_delta_cdb, digits = 2),order.by = dt_vct2)

# ANTES DE INICIAR O SERVER RODAR O SOURCE plot_base_vectors_OC.r

tbl_CDB_mercado %>% 
  filter(Peer == "Grandes bancos de Varejo",
         INDICE == "DI",
         TICKET_AJUSTADO %in% c("(H) De 10 a 20 milhões","(I) De 20 a 50 milhões", "(J) De 50 a 100 milhões","(K) Mais de 100 milhões"),
         EMISSOR == "Mercado",
         DETENTOR == "Cliente") %>% collect() -> cdb_mercado

cdb_mercado %>% 
  unite(COD,CONDICAO_RESGATE,CONDICAO_ESPECIFICA,sep="") %>% 
  filter(COD %in% c("CONDICAO A MERCADONAO","TEM CONDICAOSIM"),
         DAT_REGISTRO == "2017-06-29") %>% 
  mutate(taxa = TAXA_MEDIA * VAL_FINANCEIRO_TOTAL) %>% 
  group_by(FAIXA_PRAZO_AJUSTADO) %>% 
  summarise(soma = sum(VAL_FINANCEIRO_TOTAL), tx = sum(taxa), txmd = sum(taxa)/sum(VAL_FINANCEIRO_TOTAL)/100) -> cdb_mercado2

tbl_CDB_santander %>% 
  filter(Peer == "Grandes bancos de Varejo",
         INDICE == "DI",
         TICKET_AJUSTADO %in% c("(H) De 10 a 20 milhões","(I) De 20 a 50 milhões", "(J) De 50 a 100 milhões","(K) Mais de 100 milhões"),
         EMISSOR == "Mercado",
         DETENTOR == "Cliente") %>% collect() -> cdb_santander

cdb_santander %>% 
  unite(COD,CONDICAO_RESGATE,CONDICAO_ESPECIFICA,sep="") %>% 
  filter(COD %in% c("CONDICAO A MERCADONAO","TEM CONDICAOSIM"),
         DAT_REGISTRO == "2017-06-29") %>% 
  mutate(taxa = TAXA_MEDIA * VAL_FINANCEIRO_TOTAL) %>% 
  group_by(FAIXA_PRAZO_AJUSTADO) %>% 
  summarise(soma = sum(VAL_FINANCEIRO_TOTAL), tx = sum(taxa), txmd = sum(taxa)/sum(VAL_FINANCEIRO_TOTAL)/100) -> cdb_santander2

cdb_mercado2 %>% 
  left_join(cdb_santander2, by='FAIXA_PRAZO_AJUSTADO') %>% 
  mutate_each(funs(replace(.,is.na(.),0))) %>% 
  mutate(volXsantander = (soma.x  - soma.y)/1000000, VolSantander = soma.y/1000000) %>% 
  mutate(ShareSantander = VolSantander / (volXsantander+VolSantander)) %>% 
  mutate(txmdxsan = ((tx.x - tx.y)/(soma.x-soma.y))/100) %>% 
  mutate(DeltaSan = txmd.y - txmdxsan) -> df_press_cdb

```

## Daily Report {.tabset .tabset-fade}

### CDB (Market - Client) | Evolução - Share vs Peers (BRL MM)

```{r CDB_MC_Highcharter}

highchart(type="stock") %>% 
  hc_add_series(ts_San_Share_cdb, name = "Share", color = "red",
                dataLabels = list(align = "center", enabled = TRUE, style = list(fontSize = "20px"))) %>% 
  hc_add_series(ts_delta_cdb, type = "column", name = "Delta", color = "gray",
                dataLabels = list(align = "center", enabled = TRUE, style = list(fontSize = "20px"))) %>% 
  hc_rangeSelector(selected = 0) %>% 
  hc_legend(enabled=TRUE, align = "right", verticalAlign = "top", itemStyle= list(fontSize = "15px")) %>% 
  hc_tooltip(useHTML=TRUE,pointFormat = paste0("<span style=\"color:{point.color}\">\u25CF</span>", "{series.name}: <b>{point.y:.2f}%</b><br/>")) %>% 
  hc_xAxis(labels = list(style = list(fontSize = "15px")))

```

### Tabela de Volumes

```{r CDB_MC_tbl_vol}

df_press_cdb %>% 
  select(VolSantander) %>% 
  sum() -> total_sum_volumeSantander_cdb

df_press_cdb %>% 
  select(volXsantander) %>% 
  sum() -> total_sum_volumexsantander_cdb

total_share_cdb <- total_sum_volumeSantander_cdb / (total_sum_volumeSantander_cdb + total_sum_volumexsantander_cdb) * 100

total_vol_cdb <- c('<span style="color:black"><b>Total</b></span>',
               sprintf("<span style=\"color:black\"><b>$%.2f</b></span>",total_sum_volumeSantander_cdb),
               sprintf("<span style=\"color:black\"><b>$%.2f</b></span>",total_sum_volumexsantander_cdb),
               sprintf("<span style=\"color:black\"><b>%.2f%%</b></span>",total_share_cdb))

df_press_cdb %>% 
  select(FAIXA_PRAZO_AJUSTADO, VolSantander, volXsantander, ShareSantander) %>% 
  rbind(.,total_vol_cdb) %>% 
  DT::datatable(options = list(dom = 't'), rownames=FALSE, escape = FALSE) %>% 
  DT::formatCurrency(c('VolSantander','volXsantander')) %>% 
  DT::formatPercentage('ShareSantander',2) %>% 
  DT::formatStyle(c('VolSantander','volXsantander', 'ShareSantander'),fontWeight = 'bold')

```

### Tabela de Taxas

```{r CDB_MC_tbl_taxa}

df_press_cdb %>% 
  select(soma.y) %>% 
  sum() -> total_volsan_cdb

df_press_cdb %>% 
  select(tx.y) %>% 
  sum() -> total_txvolsan_cdb

df_press_cdb %>% 
  select(tx.x) %>% 
  sum() -> total_txvolmkt_cdb

df_press_cdb %>% 
  select(soma.x) %>% 
  sum() -> total_volmkt_cdb

total_txmd_santander_cdb <- total_txvolsan_cdb/total_volsan_cdb
total_txmd_xsantander_cdb <- (total_txvolmkt_cdb - total_txvolsan_cdb)/(total_volmkt_cdb - total_volsan_cdb)
total_delta_santander_cdb <- total_txmd_santander_cdb - total_txmd_xsantander_cdb

total_tx_cdb <- c('<span style="color:black"><b>Total</b></span>',
              sprintf("<span style=\"color:black\"><b>%.2f%%</b></span>",total_txmd_santander_cdb),
              sprintf("<span style=\"color:black\"><b>%.2f%%</b></span>",total_txmd_xsantander_cdb),
              sprintf("<span style=\"color:black\"><b>%.2f%%</b></span>",total_delta_santander_cdb))

df_press_cdb %>% 
  select(FAIXA_PRAZO_AJUSTADO,txmd.y,txmdxsan,DeltaSan) %>% 
  rbind(.,total_tx_cdb) %>% 
  DT::datatable(options = list(dom = 't'), rownames=FALSE, escape = FALSE) %>% 
  DT::formatPercentage(c('txmd.y','txmdxsan','DeltaSan'),2) %>% 
  DT::formatStyle(c('txmd.y','txmdxsan', 'DeltaSan'),fontWeight = 'bold')

```
