---
title:
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}

library(flexdashboard)
library(tidyverse)

# ANTES DE INICIAR O SERVER RODAR O SOURCE plot_base_vectors_OC.r

# DB SOCKET
db <- src_sqlite("~/R/evoapp/DB/cetip_db.sqlite3", create = FALSE)

# DB TABLES
tbl_oc_mercado <- tbl(db,"b3_oc_mercado")
tbl_oc_santander <- tbl(db,"b3_oc_santander")

tbl_oc_mercado %>% 
  filter(TICKET %in% c("(H) De 10 a 20 milhões","(I) De 20 a 50 milhões", "(J) De 50 a 100 milhões","(K) Mais de 100 milhões"),
         ATIVO == 'DEB',
         INDEXADOR == 'DI',
         TIPO_ATIVO == 'Não Leasing',
         PEER == 'Grandes bancos de Varejo',
         DAT_REGISTRO == '2017-06-26') %>% 
  mutate(taxa = TAXA_MEDIA * VAL_FINANCEIRO) %>%
  group_by(FAIXA_PRAZO) %>% 
  summarise(soma = sum(VAL_FINANCEIRO), tx = sum(taxa), txMd = sum(taxa)/sum(VAL_FINANCEIRO)/100) %>% collect() -> oc_mercado

tbl_oc_santander %>% 
  filter(TICKET %in% c("(H) De 10 a 20 milhões","(I) De 20 a 50 milhões", "(J) De 50 a 100 milhões","(K) Mais de 100 milhões"),
         ATIVO == 'DEB',
         INDEXADOR == 'DI',
         TIPO_ATIVO == 'Não Leasing',
         PEER == 'Grandes bancos de Varejo',
         DAT_REGISTRO == '2017-06-26') %>%
  mutate(taxa = TAXA_MEDIA * VAL_FINANCEIRO) %>%
  group_by(FAIXA_PRAZO) %>% 
  summarise(soma = sum(VAL_FINANCEIRO), tx = sum(taxa), txMd = sum(taxa)/sum(VAL_FINANCEIRO)/100) %>% collect() -> oc_santander

oc_mercado %>%
  left_join(oc_santander, by='FAIXA_PRAZO') %>%
  mutate_each(funs(replace(.,is.na(.),0))) %>% 
  mutate(volXsantander = (soma.x  - soma.y)/1000000, VolSantander = soma.y/1000000) %>% 
  mutate(ShareSantander = VolSantander / (volXsantander+VolSantander)) %>% 
  mutate(txmdxsan = ((tx.x - tx.y)/(soma.x-soma.y))/100) %>% 
  mutate(DeltaSan = txMd.y - txmdxsan) %>% 
  collect() -> df_press

```

Row {data-width=750}
-----------------------------------------------------------------------

### Tabela de Volumes

```{r}

df_press %>% 
  select(VolSantander) %>% 
  sum() -> total_sum_volumeSantander

df_press %>% 
  select(volXsantander) %>% 
  sum() -> total_sum_volumexsantander

total_share <- (total_sum_volumeSantander / (total_sum_volumeSantander + total_sum_volumexsantander))*100

sketch = htmltools::withTags(table(
  class = 'display',
  thead(
    tr(
      th("Faixa Prazo"),
      th("Santander"),
      th("Peer Groups"),
      th("Share")
    )
  ),
  tfoot(
    tr(
      th('Total'),
      th(sprintf(fmt="$%.2f",total_sum_volumeSantander)),
      th(sprintf(fmt="$%.2f",total_sum_volumexsantander)),
      th(sprintf(fmt="%.2f%%",total_share))
    )
  )
))
df_press %>% 
  select(FAIXA_PRAZO,VolSantander,volXsantander, ShareSantander) %>% 
  DT::datatable(options = list(dom = 't'), container = sketch, rownames=FALSE, extensions = 'Responsive') %>% 
  DT::formatCurrency(c('VolSantander','volXsantander')) %>% 
  DT::formatPercentage('ShareSantander',2)

```

Row {data-width=750}
-----------------------------------------------------------------------

### Tabela de Taxas

```{r}

df_press %>% 
  select(soma.y) %>% 
  sum() -> total_volsan

df_press %>% 
  select(tx.y) %>% 
  sum() -> total_txvolsan

df_press %>% 
  select(tx.x) %>% 
  sum() -> total_txvolmkt

df_press %>% 
  select(soma.x) %>% 
  sum() -> total_volmkt

total_txmd_santander <- total_txvolsan/total_volsan
total_txmd_xsantander <- (total_txvolmkt - total_txvolsan)/(total_volmkt - total_volsan)
total_delta_santander <- total_txmd_santander - total_txmd_xsantander

sketch = htmltools::withTags(table(
  class = 'display',
  thead(
    tr(
      th("Faixa Prazo"),
      th("Santander"),
      th("Peer Groups"),
      th("Delta")
    )
  ),
  tfoot(
    tr(
      th("Total"),
      th(sprintf(fmt="%.2f%%",total_txmd_santander)),
      th(sprintf(fmt="%.2f%%",total_txmd_xsantander)),
      th(sprintf(fmt="%.2f%%",total_delta_santander))
    )
  )
))
df_press %>% 
  select(FAIXA_PRAZO,txMd.y,txmdxsan,DeltaSan) %>% 
  DT::datatable(options = list(dom = 't'), container = sketch, rownames= FALSE, extensions = 'Responsive') %>% 
  DT::formatPercentage(c('txMd.y','txmdxsan','DeltaSan'),2)

```

