---
title:
output: 
  flexdashboard::flex_dashboard:
  orientation: rows
  
---

```{r setup, include=FALSE}

library(flexdashboard)
library(tidyverse)

# ANTES DE INICIAR O SERVER RODAR O SOURCE plot_base_vectors_OC.r

setwd('~/R/evoapp/DB/')
# DB SOCKET
db <- src_sqlite("cetip_db.sqlite3", create = FALSE)

# DB TABLES
tbl_CDB_mercado <- tbl(db,"b3_CDB_mercado")
tbl_CDB_santander <- tbl(db,"b3_CDB_santander")

tbl_CDB_mercado %>% 
  filter(Peer == "Grandes bancos de Varejo",
         INDICE == "DI",
         EMISSOR == "Mercado",
         DETENTOR == "Mercado") %>% collect() -> cdb_mercado

cdb_mercado %>% 
  unite(COD,CONDICAO_RESGATE,CONDICAO_ESPECIFICA,sep="") %>% 
  filter(COD %in% c("CONDICAO A MERCADONAO","TEM CONDICAOSIM"),
         DAT_REGISTRO == "2017-06-26") %>% 
  mutate(taxa = TAXA_MEDIA * VAL_FINANCEIRO_TOTAL) %>% 
  group_by(FAIXA_PRAZO_AJUSTADO) %>% 
  summarise(soma = sum(VAL_FINANCEIRO_TOTAL), tx = sum(taxa), txmd = sum(taxa)/sum(VAL_FINANCEIRO_TOTAL)/100) -> cdb_mercado2

tbl_CDB_santander %>% 
  filter(Peer == "Grandes bancos de Varejo",
         INDICE == "DI",
         EMISSOR == "Mercado",
         DETENTOR == "Mercado") %>% collect() -> cdb_santander

cdb_santander %>% 
  unite(COD,CONDICAO_RESGATE,CONDICAO_ESPECIFICA,sep="") %>% 
  filter(COD %in% c("CONDICAO A MERCADONAO","TEM CONDICAOSIM"),
         DAT_REGISTRO == "2017-06-26") %>% 
  mutate(taxa = TAXA_MEDIA * VAL_FINANCEIRO_TOTAL) %>% 
  group_by(FAIXA_PRAZO_AJUSTADO) %>% 
  summarise(soma = sum(VAL_FINANCEIRO_TOTAL), tx = sum(taxa), txmd = sum(taxa)/sum(VAL_FINANCEIRO_TOTAL)/100) -> cdb_santander2

cdb_mercado2 %>% 
  left_join(cdb_santander2, by='FAIXA_PRAZO_AJUSTADO') %>% 
  mutate_each(funs(replace(.,is.na(.),0))) %>% 
  mutate(volXsantander = (soma.x  - soma.y)/1000000, VolSantander = soma.y/1000000) %>% 
  mutate(ShareSantander = VolSantander / (volXsantander+VolSantander)) %>% 
  mutate(txmdxsan = ((tx.x - tx.y)/(soma.x-soma.y))/100) %>% 
  mutate(DeltaSan = txmd.y - txmdxsan) -> df_press_cdb


```

Row {data-height=650}
-----------------------------------------------------------------------

### Tabela de Volumes

```{r}

df_press_cdb %>% 
  select(VolSantander) %>% 
  sum() -> total_sum_volumeSantander_cdb

df_press_cdb %>% 
  select(volXsantander) %>% 
  sum() -> total_sum_volumexsantander_cdb

total_share_cdb <- total_sum_volumeSantander_cdb / (total_sum_volumeSantander_cdb + total_sum_volumexsantander_cdb) * 100

sketch = htmltools::withTags(table(
  class = 'display',
  thead(
    tr(
      th("Faixa Prazo"),
      th("Santander"),
      th("Peer Groups"),
      th("Share")
    )
  ),
  tfoot(
    tr(
      th('Total'),
      th(sprintf(fmt="$%.2f",total_sum_volumeSantander_cdb)),
      th(sprintf(fmt="$%.2f",total_sum_volumexsantander_cdb)),
      th(sprintf(fmt="%.2f%%",total_share_cdb))
    )
  )
))
df_press_cdb %>% 
  select(FAIXA_PRAZO_AJUSTADO, VolSantander, volXsantander, ShareSantander) %>% 
  DT::datatable(options = list(dom = 't'), container = sketch, rownames=FALSE) %>% 
  DT::formatCurrency(c('VolSantander','volXsantander')) %>% 
  DT::formatPercentage('ShareSantander',2)

```

Row {data-height=650}
-----------------------------------------------------------------------

### Tabela de Taxas

```{r}

df_press_cdb %>% 
  select(soma.y) %>% 
  sum() -> total_volsan_cdb

df_press_cdb %>% 
  select(tx.y) %>% 
  sum() -> total_txvolsan_cdb

df_press_cdb %>% 
  select(tx.x) %>% 
  sum() -> total_txvolmkt_cdb

df_press_cdb %>% 
  select(soma.x) %>% 
  sum() -> total_volmkt_cdb

total_txmd_santander_cdb <- total_txvolsan_cdb/total_volsan_cdb
total_txmd_xsantander_cdb <- (total_txvolmkt_cdb - total_txvolsan_cdb)/(total_volmkt_cdb - total_volsan_cdb)
total_delta_santander_cdb <- total_txmd_santander_cdb - total_txmd_xsantander_cdb

sketch = htmltools::withTags(table(
  class = 'display',
  thead(
    tr(
      th("Faixa Prazo"),
      th("Santander"),
      th("Peer Groups"),
      th("Delta")
    )
  ),
  tfoot(
    tr(
      th("Total"),
      th(sprintf(fmt="%.2f%%",total_txmd_santander_cdb)),
      th(sprintf(fmt="%.2f%%",total_txmd_xsantander_cdb)),
      th(sprintf(fmt="%.2f%%",total_delta_santander_cdb))
    )
  )
))
df_press_cdb %>% 
  select(FAIXA_PRAZO_AJUSTADO,txmd.y,txmdxsan,DeltaSan) %>% 
  DT::datatable(options = list(dom = 't'), container = sketch, rownames= FALSE) %>% 
  DT::formatPercentage(c('txmd.y','txmdxsan','DeltaSan'),2)

```